### ISSUE TITLE
ARC support.

### ISSUE THREAD

**Issue by Panajev** [krzysztofzablocki/CCNode-SFGestureRecognizers#1]
Please add ARC support to your nice new class.

**Comment by krzysztofzablocki** [comment]
Done. Works automatic so you can use it for both ARC and non ARC projects without any changes ;)

**Comment by Panajev** [comment]
Awesome, could you also add a small sample app?

Thank you!

2012/3/15 Krzysztof Zabłocki <
reply@reply.github.com

**Comment by krzysztofzablocki** [comment]
I already did it when adding arc, look at the repo:)

**Comment by Panajev** [comment]
Sorry, did not look at the repo first. Good job, the Cocos2D community will
appreciate it :)!

2012/3/15 Krzysztof Zabłocki <
reply@reply.github.com

**Comment by krzysztofzablocki** [comment]
There was a wrong version, I just fixed it. If you encounter any problems with newest version let me know
