### ISSUE TITLE
Issue with UIPopover / UIWebview over the top of cocos2d scene using SFGestureRecognizers

### ISSUE THREAD

**Issue by pkester** [krzysztofzablocki/CCNode-SFGestureRecognizers#2]
When you use a UIPopover over a scene with UIGestures added, you get objc_release errors while using ARC.

**\* -[_UIWebViewScrollView release]: message sent to deallocated instance 0x21cb01b0

See https://github.com/pkester/webViewTest-Cocos2D for test case.  (Press the bon button twice)

**Comment by krzysztofzablocki** [comment]
Works fine under xcode 4.5.1 ( sim + ipad 3 ), it will only crash on cocos display link when clicking very quickly many times but that not gesture issue.

**Comment by pkester** [comment]
Strange. I am running Xcode 4.5.1 (4G1004) with sim and an ipad3, both the sample app and my own app will crash every time ARC releases the popover, so every 2nd time the popover is opened.

Here is a short video showing it happen, first time without NSZombie enabled, second time with.

http://screencast.com/t/5fdeZ35hk6

**Comment by krzysztofzablocki** [comment]
Hey mate,
You were right, for some reason when using popover something weird was going on with the gestures. I moved away from modifying global class tree and instead changes are now applied only to category classes.
Try running your code with newest changes and let me know if it helped

**Comment by pkester** [comment]
Great work Krzysztof, this fixes the issue perfectly.

**Comment by tonisalae** [comment]
Same thing happens when using UITableView with cocos 2.x and ARC

**Comment by krzysztofzablocki** [comment]
It used to, but not with newest version :) http://foldifyapp.com is using gestures everywhere and have tableviews in popovers, works fine.

**Comment by tonisalae** [comment]
Ups! You are right, sir. Thank you!

**Comment by krzysztofzablocki** [comment]
You need to have newest version of category, it's no longer affecting any other gesture recognisers except the ones you add to cocos.

**Comment by postmechanical** [comment]
Yes. Pulled latest source but needed to do clean build apparently to get it working. All set now. Thanks!
