### ISSUE TITLE
negative coordinates problem

### ISSUE THREAD

**Issue by lukasa1993** [krzysztofzablocki/CCNode-SFGestureRecognizers#3]
gesture recognition doesn't work when node's coordinates is in negative values can i don anything with that?

**Comment by krzysztofzablocki** [comment]
What exactly do you mean? Pos shouldnt matter as long as view touchRect is still partially visible on screen.

**Comment by lukasa1993** [comment]
yes i found that but i wasn't change touchRect-value, now i set it manually i don't know why its happens i just  use setPosition but with negative X - sometimes

**Comment by krzysztofzablocki** [comment]
Can you prepare a sample project showing your Issue? The current sample on Github allows you to move objects to negative coordinates and works fine.
