### ISSUE TITLE
Cocos2d-x migration

### ISSUE THREAD

**Issue by garudaonekh** [krzysztofzablocki/CCNode-SFGestureRecognizers#7]
Hi,
great tool. any Cocos2d-x implementation of this?

And how hard it's to convert it to Cocos2d-x?

Thanks;

**Comment by bagusflyer** [comment]
This is also what I want to ask?

**Comment by krzysztofzablocki** [comment]
cocos2d-x is multiplatform and thus there is no UIGestureRecognizer concept as far as I know ?

**Comment by garudaonekh** [comment]
There're several implementation of UIGestureRecognizer in cocos2d-x

Ex.
https://github.com/spalx/cocos2d-x-extensions

**Comment by krzysztofzablocki** [comment]
I think the problem would be that C++ is not as dynamic as Objective-C.
This category is using runtime to inject support for native gesture recognisers into cocos2d, in C++ you wouldn't be able to do that dynamically, thus probably only way to have gesture recognisers in CCNode in cocos2d-x is to get it in normal implementation.

**Comment by gitsome** [comment]
How about cocos2d v3? I know layers have been done away with. Would this be compatible with v3 with little modification?

**Comment by krzysztofzablocki** [comment]
@gitsome added v3 in last commit

**Comment by gitsome** [comment]
Awesome @krzysztofzablocki !  Thank you so much. This will make my life sooo much easier!
